# Delete these routes and define your own shop routes here

roma_sylius_product_variant_static_welcome:
    path: /static-welcome/{name}
    defaults:
        _controller: Roma\SyliusProductVariantPlugin\Controller\GreetingController::staticallyGreetAction
        name: ~

roma_sylius_product_variant_dynamic_welcome:
    path: /dynamic-welcome/{name}
    defaults:
        _controller: Roma\SyliusProductVariantPlugin\Controller\GreetingController::dynamicallyGreetAction
        name: ~
